# Generated by Django 3.0.1 on 2019-12-28 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecturer_name', models.CharField(max_length=100)),
                ('batch', models.IntegerField(choices=[(1, '1st Year'), (2, '2nd Year'), (3, '3rd Year'), (4, '4th Year')])),
                ('hall', models.IntegerField(choices=[(4, 'NLH'), (5, '204'), (6, '104'), (7, 'CIS Lab 1'), (8, 'CIS Lab 2')])),
                ('subject', models.CharField(max_length=50)),
                ('students', models.IntegerField()),
            ],
        ),
    ]
