# Generated by Django 3.0.1 on 2020-03-30 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('altg_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllBatches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_no', models.CharField(max_length=20)),
                ('batch_name_suffix', models.CharField(max_length=20)),
                ('no_of_students', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AllSemesters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_no', models.CharField(max_length=20)),
                ('semester_name_suffix', models.CharField(max_length=20)),
            ],
        ),
    ]
