# Generated by Django 3.0.1 on 2020-03-24 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('altg_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='extra_column',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
