# Generated by Django 3.0.1 on 2020-02-02 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('altg_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processdata',
            name='batch',
            field=models.IntegerField(choices=[('1st', '1st Year'), ('2nd', '2nd Year'), ('3rd', '3rd Year'), ('4th', '4th Year')]),
        ),
        migrations.AlterField(
            model_name='processdata',
            name='hall',
            field=models.IntegerField(choices=[('NLH', 'NLH'), ('204', '204'), ('104', '104'), ('cis1', 'CIS Lab 1'), ('cis2', 'CIS Lab 2')]),
        ),
    ]
