# Generated by Django 3.0.1 on 2020-03-24 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('altg_app', '0002_subjects_extra_column'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjects',
            name='extra_column',
        ),
    ]
