# Generated by Django 3.0.1 on 2020-02-05 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('altg_app', '0003_persons'),
    ]

    operations = [
        migrations.CreateModel(
            name='LectureHalls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hall_number', models.CharField(max_length=224)),
                ('hall_name', models.CharField(max_length=224)),
            ],
        ),
    ]
