# Generated by Django 3.0.1 on 2020-04-30 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('altg_app', '0004_delete_generatedschedules'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedSchedules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecturer_name', models.CharField(max_length=224)),
                ('semester', models.CharField(max_length=20)),
                ('hall_n_time', models.CharField(max_length=224)),
                ('schedule', models.CharField(max_length=500)),
            ],
        ),
    ]
