# Generated by Django 3.0.1 on 2020-03-24 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('altg_app', '0004_allsubjects'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subjects',
        ),
    ]
