# Generated by Django 3.0.1 on 2020-03-24 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('altg_app', '0005_delete_subjects'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LectureHalls',
            new_name='AllLectureHalls',
        ),
    ]
