# Generated by Django 3.0.1 on 2020-04-30 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('altg_app', '0005_generatedschedules'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GeneratedSchedules',
        ),
    ]
