# Generated by Django 3.0.1 on 2020-02-15 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('altg_app', '0006_auto_20200215_1230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subjects',
            old_name='rel_batch',
            new_name='related_batch',
        ),
    ]
