# Generated by Django 3.0.1 on 2020-03-24 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('altg_app', '0006_auto_20200324_1731'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AllLectureHalls',
            new_name='LectureHalls',
        ),
    ]
