# Generated by Django 3.0.1 on 2020-03-24 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('altg_app', '0008_alllecturehalls'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LectureHalls',
        ),
    ]
