# Generated by Django 3.0.1 on 2020-02-18 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('altg_app', '0009_auto_20200218_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturers',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='lecturers',
            name='last_name',
        ),
        migrations.AddField(
            model_name='lecturers',
            name='lecturer_name',
            field=models.CharField(default=None, max_length=224),
        ),
    ]
