# Generated by Django 3.0.1 on 2020-02-19 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('altg_app', '0010_auto_20200218_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='related_lecturer',
            field=models.CharField(default='', max_length=224),
        ),
    ]
