# Generated by Django 3.0.1 on 2020-03-24 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('altg_app', '0010_auto_20200324_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_profile',
            field=models.ImageField(upload_to='users/'),
        ),
    ]
