# Generated by Django 3.0.1 on 2020-03-25 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('altg_app', '0011_auto_20200324_2101'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=224)),
                ('user_profile', models.ImageField(upload_to='users/')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_profile',
        ),
    ]
