# Generated by Django 3.0.1 on 2020-02-19 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('altg_app', '0011_subjects_related_lecturer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lecturers',
            new_name='User',
        ),
    ]
