# Generated by Django 3.0.1 on 2020-03-25 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('altg_app', '0012_auto_20200325_1202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profiles',
            old_name='user_profile',
            new_name='user_profile_img',
        ),
    ]
