# Generated by Django 3.0.1 on 2020-03-25 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('altg_app', '0013_auto_20200325_1533'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profiles',
            old_name='username',
            new_name='user_id',
        ),
    ]
