# Generated by Django 3.0.1 on 2020-03-25 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('altg_app', '0014_auto_20200325_1627'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profiles',
            old_name='user_id',
            new_name='username',
        ),
    ]
