# Generated by Django 3.0.1 on 2020-02-19 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('altg_app', '0014_auto_20200219_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password_confirm',
        ),
    ]
