# Generated by Django 3.0.1 on 2020-04-30 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('altg_app', '0006_delete_generatedschedules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedschedules',
            name='hall_n_time',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='savedschedules',
            name='schedule',
            field=models.CharField(max_length=1000),
        ),
    ]
